
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;

import javax.swing.JButton;
import javax.swing.JFrame;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.border.TitledBorder;
import javax.swing.UIManager;
import java.awt.Color;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.GridLayout;
import javax.swing.JLabel;
import java.awt.CardLayout;
import java.awt.Component;

import javax.imageio.ImageIO;
import javax.swing.Box;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alek
 */
@SuppressWarnings("serial")
public class GarageBandView extends JFrame {

	public GarageBandPlayer player;
	public GarageBandController controller;

	/**
	 * Creates new form GarageBandView
	 */
	public GarageBandView() {
		getContentPane().setMaximumSize(new Dimension(1920, 1080));
		lista2= new ArrayList<JButton>();
		initComponents();
		this.setSize(1232, 548);
		lista = new ArrayList<JButton>();
		inicjalizuj();
		this.setTitle("GarageBand:D");
		setFocusable(true);

		setVisible(true);
		requestFocusInWindow();
		
		Integer liczba = 123;
		String cokolwiek= liczba.toString();
		//System.out.print(cokolwiek);
		cokolwiek.length();
		//System.out.print(cokolwiek.codePointAt(1));
		char[] tab = new char[5];
		cokolwiek.getChars(0, cokolwiek.length(), tab, 0);
		System.out.println(tab[2]);
		
		
		 for (JButton przycisk : lista) { 
			 przycisk.setOpaque(false);
			 przycisk.setContentAreaFilled(false);
			 //przycisk.setBorderPainted(false); 
		 }
		 


	}

	protected void registerPlayer(GarageBandPlayer x) {
		panel_keyboard.player = x;
		player = x;
	}
	
	protected void registerPlayerPiano(GarageBandPlayer x) {
		
	}

	protected void registerListener(GarageBandController x) {
		controller = x;
		this.addKeyListener(x);
		jPanel2.addKeyListener(x);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">

	private void initComponents() {

		jPanel2 = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel2.setLayout(null);

		panel = new JPanel();
		panel.setBorder(new TitledBorder(UIManager.getBorder("TitledBorder.border"), "Menu", TitledBorder.CENTER,
				TitledBorder.TOP, null, new Color(0, 0, 0)));
		panel.setBounds(973, 16, 260, 461);
		jPanel2.add(panel);
		panel.setLayout(null);
		jButton43 = new javax.swing.JButton();
		jButton43.setBounds(96, 76, 50, 50);
		panel.add(jButton43);

		jButton43.setIcon(new javax.swing.ImageIcon("./graphics/pianino ikonka.png"));
		jButton43.setBackground(new java.awt.Color(255, 51, 102));
		jButton43.setForeground(new java.awt.Color(255, 255, 102));
		jButton44 = new javax.swing.JButton();
		jButton44.setBounds(176, 76, 50, 50);
		panel.add(jButton44);

		jButton44.setIcon(new javax.swing.ImageIcon("./graphics/bass ikonka.png"));
		jButton44.setBackground(new java.awt.Color(255, 51, 102));
		jButton44.setForeground(new java.awt.Color(255, 255, 102));
		jButton45 = new javax.swing.JButton();
		jButton45.setBounds(16, 76, 50, 50);
		panel.add(jButton45);

		jButton45.setIcon(new javax.swing.ImageIcon("./graphics/gitara ikona.jpg"));
		jButton45.setBackground(new java.awt.Color(255, 51, 102));
		jButton45.setForeground(new java.awt.Color(255, 255, 102));
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setBounds(56, 306, 120, 30);
		panel.add(jLabel3);

		jLabel3.setBackground(new java.awt.Color(0, 0, 0));
		jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
		jLabel3.setText("Nauka Gry");
		jLabel4 = new javax.swing.JLabel();
		jLabel4.setBounds(56, 16, 140, 30);
		panel.add(jLabel4);

		jLabel4.setBackground(new java.awt.Color(0, 0, 0));
		jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
		jLabel4.setText("Instrumenty");
		jLabel5 = new javax.swing.JLabel();
		jLabel5.setBounds(26, 156, 200, 30);
		panel.add(jLabel5);

		jLabel5.setBackground(new java.awt.Color(0, 0, 0));
		jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
		jLabel5.setText("Zapisz i Odtwórz");

		jComboBox1 = new javax.swing.JComboBox<>();
		jComboBox1.setBounds(36, 346, 170, 30);
		panel.add(jComboBox1);

		jComboBox1.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Smoke on the water", "Breaking the law", "Nemo" }));
		jButton46 = new javax.swing.JButton();
		jButton46.setBounds(66, 206, 50, 50);
		panel.add(jButton46);

		jButton46.setIcon(new javax.swing.ImageIcon("./graphics/play.jpg"));
		jButton47 = new javax.swing.JButton();
		jButton47.setBounds(126, 206, 50, 50);
		panel.add(jButton47);

		jButton47.setIcon(new javax.swing.ImageIcon("./graphics/pauza.png"));
		jButton48 = new javax.swing.JButton();
		jButton48.setBounds(186, 206, 50, 50);
		panel.add(jButton48);

		jButton48.setIcon(new javax.swing.ImageIcon("./graphics/stop.png"));
		jButton49 = new javax.swing.JButton();
		jButton49.setBounds(6, 206, 50, 50);
		panel.add(jButton49);

		jButton49.setIcon(new javax.swing.ImageIcon("./graphics/zapis2.png"));
		jButton50 = new javax.swing.JButton();
		jButton50.setBounds(126, 396, 50, 50);
		panel.add(jButton50);

		jButton50.setIcon(new javax.swing.ImageIcon("./graphics/stop.png"));
		
		jButton50.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
				
				controller.koniecNauki();
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
			}
		});
		
		jButton51 = new javax.swing.JButton();
		jButton51.setBounds(56, 396, 50, 50);
		panel.add(jButton51);

		jButton51.setIcon(new javax.swing.ImageIcon("./graphics/play.jpg"));
		
		jButton52 = new javax.swing.JButton();
		jButton52.setBounds(53, 270, 135, 30);
		jButton52.setText("Wybierz plik...");
		panel.add(jButton52);
		
		jButton52.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
				
				player.startSong(0); 		//troche nie pasuje mi ze okienko menedzera i ogolnie wybieranie pliku do odtworzenia
											//jest w plejerze, ale niech juz tak zostanie, zrobimy taka prowizoryczn¹ parametryzacjê
											//zeby odroznic dzialanie "play" i "wybierz plik..."
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
			}
		});



		jButton51.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
				
				controller.naukaGry((String)(jComboBox1.getSelectedItem()),lista,panel_keyboard.lista,lista2,panel_guitar.isVisible()?(char)25:(char)34);

			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
			}
		});

		jButton49.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
				player.startRec(); ////////////////////////////////////////////////
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
			}
		});

		jButton48.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
				player.stopRec();
				player.stopSong();
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
			}
		});
		jButton47.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
				player.pauseSong();
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
			}
		});

		jButton46.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {

				// player.setInstrument((char)30);
				player.startSong(1); ////////////////////////////////////////////////

			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
			}
		});
		jButton45.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.setInstrument((char) 25);
				player.setShift(0);
				panel_bass.setVisible(false);
				panel_keyboard.setVisible(false);
				panel_guitar.setVisible(true);
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {

			}
		});
		jButton44.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.setInstrument((char) 34);
				player.setShift(0);
				panel_keyboard.setVisible(false);
				panel_guitar.setVisible(false);
				panel_bass.setVisible(true);
				/*
				 * 32 Acoustic Bs. 33 Fingered Bs. 34 Picked Bs. 35 Fretless Bs.
				 * 36 Slap Bass 1 37 Slap Bass 2 38 Synth Bass 1 39 Synth Bass 2
				 */
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
			}
		});
		jButton43.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.setInstrument((char) 0);
				player.setShift(-12);
				panel_guitar.setVisible(false);
				panel_bass.setVisible(false);
				panel_keyboard.setVisible(true);
				
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {

			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(jPanel2,
				Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 1211, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 496, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(549, Short.MAX_VALUE)));

		panel_instrument = new JPanel();
		panel_instrument.setBounds(0, 16, 963, 461);
		jPanel2.add(panel_instrument);
		panel_instrument.setLayout(new CardLayout(0, 0));

		panel_guitar = new JPanel();
		panel_instrument.add(panel_guitar, "name_25798938465449");
		panel_guitar.setBorder(new TitledBorder(UIManager.getBorder("TitledBorder.border"), "Instrument",
				TitledBorder.LEADING, TitledBorder.TOP, null, new Color(0, 0, 0)));
		panel_guitar.setLayout(null);
		jButton1 = new javax.swing.JButton();
		jButton1.setBounds(9, 19, 164, 36);
		jButton1.setAlignmentY(0.0f);
		panel_guitar.add(jButton1);
		jButton1.setBackground(new java.awt.Color(255, 51, 102));
		jButton1.setForeground(new java.awt.Color(255, 255, 102));

		jButton1.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 64);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 64);
				requestFocusInWindow();
			}
		});
		jButton2 = new javax.swing.JButton();
		jButton2.setBounds(170, 19, 155, 36);
		jButton2.setAlignmentY(0.0f);
		panel_guitar.add(jButton2);

		jButton2.setBackground(new java.awt.Color(255, 51, 102));
		jButton2.setForeground(new java.awt.Color(255, 255, 102));

		jButton2.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 65);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 65);
			}
		});

		jButton3 = new javax.swing.JButton();
		jButton3.setBounds(324, 19, 143, 36);
		jButton3.setAlignmentY(0.0f);
		panel_guitar.add(jButton3);

		jButton3.setBackground(new java.awt.Color(255, 51, 102));
		jButton3.setForeground(new java.awt.Color(255, 255, 102));
		jButton3.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 66);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 66);
			}
		});
		jButton4 = new javax.swing.JButton();
		jButton4.setBounds(466, 19, 139, 36);
		jButton4.setAlignmentY(0.0f);
		panel_guitar.add(jButton4);

		jButton4.setBackground(new java.awt.Color(255, 51, 102));
		jButton4.setForeground(new java.awt.Color(255, 255, 102));
		jButton4.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 67);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 67);
			}
		});
		jButton5 = new javax.swing.JButton();
		jButton5.setBounds(603, 19, 123, 36);
		jButton5.setAlignmentY(0.0f);
		panel_guitar.add(jButton5);

		jButton5.setBackground(new java.awt.Color(255, 51, 102));
		jButton5.setForeground(new java.awt.Color(255, 255, 102));
		jButton5.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 68);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 68);
			}
		});
		jButton6 = new javax.swing.JButton();
		jButton6.setBounds(725, 19, 116, 36);
		jButton6.setAlignmentY(0.0f);
		panel_guitar.add(jButton6);

		jButton6.setBackground(new java.awt.Color(255, 49, 100));
		jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		jButton6.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 69);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 69);
			}
		});
		jButton7 = new javax.swing.JButton();
		jButton7.setBounds(840, 19, 113, 36);
		jButton7.setAlignmentY(0.0f);
		panel_guitar.add(jButton7);

		jButton7.setBackground(new java.awt.Color(255, 51, 102));
		jButton7.setForeground(new java.awt.Color(255, 255, 102));
		jButton7.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 70);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 70);
			}
		});
		jButton8 = new javax.swing.JButton();
		jButton8.setBounds(9, 55, 164, 36);
		jButton8.setAlignmentY(0.0f);
		panel_guitar.add(jButton8);

		jButton8.setBackground(new java.awt.Color(255, 51, 102));
		jButton8.setForeground(new java.awt.Color(255, 255, 102));
		jButton8.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 59);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 59);
			}
		});
		jButton9 = new javax.swing.JButton();
		jButton9.setBounds(170, 55, 155, 36);
		jButton9.setAlignmentY(0.0f);
		panel_guitar.add(jButton9);

		jButton9.setBackground(new java.awt.Color(255, 51, 102));
		jButton9.setForeground(new java.awt.Color(255, 255, 102));
		jButton9.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 60);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 60);
			}
		});
		jButton10 = new javax.swing.JButton();
		jButton10.setBounds(324, 55, 143, 36);
		jButton10.setAlignmentY(0.0f);
		panel_guitar.add(jButton10);

		jButton10.setBackground(new java.awt.Color(255, 51, 102));
		jButton10.setForeground(new java.awt.Color(255, 255, 102));
		jButton10.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 61);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 61);
			}
		});
		jButton11 = new javax.swing.JButton();
		jButton11.setBounds(466, 55, 139, 36);
		jButton11.setAlignmentY(0.0f);
		panel_guitar.add(jButton11);

		jButton11.setBackground(new java.awt.Color(255, 51, 102));
		jButton11.setForeground(new java.awt.Color(255, 255, 102));
		jButton11.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 62);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 62);
			}
		});
		jButton12 = new javax.swing.JButton();
		jButton12.setBounds(603, 55, 123, 36);
		jButton12.setAlignmentY(0.0f);
		panel_guitar.add(jButton12);
		jButton12.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
			}
		});

		jButton12.setBackground(new java.awt.Color(255, 51, 102));
		jButton12.setForeground(new java.awt.Color(255, 255, 102));
		jButton12.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 63);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 63);
			}
		});
		jButton13 = new javax.swing.JButton();
		jButton13.setBounds(725, 55, 116, 36);
		jButton13.setAlignmentY(0.0f);
		panel_guitar.add(jButton13);

		jButton13.setBackground(new java.awt.Color(255, 51, 102));
		jButton13.setForeground(new java.awt.Color(255, 255, 102));
		jButton13.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 64);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 64);
			}
		});
		jButton14 = new javax.swing.JButton();
		jButton14.setBounds(840, 55, 113, 36);
		jButton14.setAlignmentY(0.0f);
		panel_guitar.add(jButton14);

		jButton14.setBackground(new java.awt.Color(255, 51, 102));
		jButton14.setForeground(new java.awt.Color(255, 255, 102));
		jButton14.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 65);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 65);
			}
		});
		jButton15 = new javax.swing.JButton();
		jButton15.setBounds(9, 91, 164, 36);
		jButton15.setAlignmentY(0.0f);
		panel_guitar.add(jButton15);

		jButton15.setBackground(new java.awt.Color(255, 51, 102));
		jButton15.setForeground(new java.awt.Color(255, 255, 102));
		jButton15.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 55);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 55);
			}
		});
		jButton16 = new javax.swing.JButton();
		jButton16.setBounds(170, 91, 155, 36);
		jButton16.setAlignmentY(0.0f);
		panel_guitar.add(jButton16);

		jButton16.setBackground(new java.awt.Color(255, 51, 102));
		jButton16.setForeground(new java.awt.Color(255, 255, 102));
		jButton16.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 56);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 56);
			}
		});
		jButton17 = new javax.swing.JButton();
		jButton17.setBounds(324, 91, 143, 36);
		jButton17.setAlignmentY(0.0f);
		panel_guitar.add(jButton17);

		jButton17.setBackground(new java.awt.Color(255, 51, 102));
		jButton17.setForeground(new java.awt.Color(255, 255, 102));
		jButton17.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 57);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 57);
			}
		});
		jButton18 = new javax.swing.JButton();
		jButton18.setBounds(466, 91, 139, 36);
		jButton18.setAlignmentY(0.0f);
		panel_guitar.add(jButton18);

		jButton18.setBackground(new java.awt.Color(255, 51, 102));
		jButton18.setForeground(new java.awt.Color(255, 255, 102));
		jButton18.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 58);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 58);
			}
		});
		jButton19 = new javax.swing.JButton();
		jButton19.setBounds(603, 91, 123, 36);
		jButton19.setAlignmentY(0.0f);
		panel_guitar.add(jButton19);

		jButton19.setBackground(new java.awt.Color(255, 51, 102));
		jButton19.setForeground(new java.awt.Color(255, 255, 102));
		jButton19.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 59);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 59);
			}
		});
		jButton20 = new javax.swing.JButton();
		jButton20.setBounds(725, 91, 116, 36);
		jButton20.setAlignmentY(0.0f);
		panel_guitar.add(jButton20);

		jButton20.setBackground(new java.awt.Color(255, 51, 102));
		jButton20.setForeground(new java.awt.Color(255, 255, 102));
		jButton20.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 60);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 60);
			}
		});
		jButton21 = new javax.swing.JButton();
		jButton21.setBounds(840, 91, 113, 36);
		jButton21.setAlignmentY(0.0f);
		panel_guitar.add(jButton21);

		jButton21.setBackground(new java.awt.Color(255, 51, 102));
		jButton21.setForeground(new java.awt.Color(255, 255, 102));
		jButton21.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 61);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 61);
			}
		});
		jButton22 = new javax.swing.JButton();
		jButton22.setBounds(9, 127, 164, 36);
		jButton22.setAlignmentY(0.0f);
		panel_guitar.add(jButton22);

		jButton22.setBackground(new java.awt.Color(255, 51, 102));
		jButton22.setForeground(new java.awt.Color(255, 255, 102));
		jButton22.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 50);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 50);
			}
		});
		jButton23 = new javax.swing.JButton();
		jButton23.setBounds(170, 127, 155, 36);
		jButton23.setAlignmentY(0.0f);
		panel_guitar.add(jButton23);

		jButton23.setBackground(new java.awt.Color(255, 51, 102));
		jButton23.setForeground(new java.awt.Color(255, 255, 102));
		jButton23.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 51);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 51);
			}
		});
		jButton24 = new javax.swing.JButton();
		jButton24.setBounds(324, 127, 143, 36);
		jButton24.setAlignmentY(0.0f);
		panel_guitar.add(jButton24);

		jButton24.setBackground(new java.awt.Color(255, 51, 102));
		jButton24.setForeground(new java.awt.Color(255, 255, 102));
		jButton24.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 52);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 52);
			}
		});
		jButton25 = new javax.swing.JButton();
		jButton25.setBounds(466, 127, 139, 36);
		jButton25.setAlignmentY(0.0f);
		panel_guitar.add(jButton25);

		jButton25.setBackground(new java.awt.Color(255, 51, 102));
		jButton25.setForeground(new java.awt.Color(255, 255, 102));
		jButton25.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 53);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 53);
			}
		});
		jButton26 = new javax.swing.JButton();
		jButton26.setBounds(603, 127, 123, 36);
		jButton26.setAlignmentY(0.0f);
		panel_guitar.add(jButton26);

		jButton26.setBackground(new java.awt.Color(255, 51, 102));
		jButton26.setForeground(new java.awt.Color(255, 255, 102));
		jButton26.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 54);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 54);
			}
		});
		jButton27 = new javax.swing.JButton();
		jButton27.setBounds(725, 127, 116, 36);
		jButton27.setAlignmentY(0.0f);
		panel_guitar.add(jButton27);

		jButton27.setBackground(new java.awt.Color(255, 51, 102));
		jButton27.setForeground(new java.awt.Color(255, 255, 102));
		jButton27.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 55);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 55);
			}
		});
		jButton28 = new javax.swing.JButton();
		jButton28.setBounds(840, 127, 113, 36);
		jButton28.setAlignmentY(0.0f);
		panel_guitar.add(jButton28);

		jButton28.setBackground(new java.awt.Color(255, 51, 102));
		jButton28.setForeground(new java.awt.Color(255, 255, 102));
		jButton28.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 56);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 56);
			}
		});
		jButton29 = new javax.swing.JButton();
		jButton29.setBounds(9, 163, 164, 36);
		jButton29.setAlignmentY(0.0f);
		panel_guitar.add(jButton29);

		jButton29.setBackground(new java.awt.Color(255, 51, 102));
		jButton29.setForeground(new java.awt.Color(255, 255, 102));
		jButton29.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 45);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 45);
			}
		});
		jButton30 = new javax.swing.JButton();
		jButton30.setBounds(170, 163, 155, 36);
		jButton30.setAlignmentY(0.0f);
		panel_guitar.add(jButton30);

		jButton30.setBackground(new java.awt.Color(255, 51, 102));
		jButton30.setForeground(new java.awt.Color(255, 255, 102));
		jButton30.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 46);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 46);
			}
		});
		jButton31 = new javax.swing.JButton();
		jButton31.setBounds(324, 163, 143, 36);
		jButton31.setAlignmentY(0.0f);
		panel_guitar.add(jButton31);

		jButton31.setBackground(new java.awt.Color(255, 51, 102));
		jButton31.setForeground(new java.awt.Color(255, 255, 102));
		jButton31.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 47);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 47);
			}
		});
		jButton32 = new javax.swing.JButton();
		jButton32.setBounds(466, 163, 139, 36);
		jButton32.setAlignmentY(0.0f);
		panel_guitar.add(jButton32);

		jButton32.setBackground(new java.awt.Color(255, 51, 102));
		jButton32.setForeground(new java.awt.Color(255, 255, 102));
		jButton32.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 48);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 48);
			}
		});
		jButton33 = new javax.swing.JButton();
		jButton33.setBounds(603, 163, 123, 36);
		jButton33.setAlignmentY(0.0f);
		panel_guitar.add(jButton33);

		jButton33.setBackground(new java.awt.Color(255, 51, 102));
		jButton33.setForeground(new java.awt.Color(255, 255, 102));
		jButton33.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 49);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 49);
			}
		});
		jButton34 = new javax.swing.JButton();
		jButton34.setBounds(725, 163, 116, 36);
		jButton34.setAlignmentY(0.0f);
		panel_guitar.add(jButton34);

		jButton34.setBackground(new java.awt.Color(255, 51, 102));
		jButton34.setForeground(new java.awt.Color(255, 255, 102));
		jButton34.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 50);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 50);
			}
		});
		jButton35 = new javax.swing.JButton();
		jButton35.setBounds(840, 163, 113, 36);
		jButton35.setAlignmentY(0.0f);
		panel_guitar.add(jButton35);

		jButton35.setBackground(new java.awt.Color(255, 51, 102));
		jButton35.setForeground(new java.awt.Color(255, 255, 102));
		jButton35.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 51);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 51);
			}
		});
		jButton36 = new javax.swing.JButton();
		jButton36.setBounds(9, 199, 164, 36);
		jButton36.setAlignmentY(0.0f);
		panel_guitar.add(jButton36);

		jButton36.setBackground(new java.awt.Color(255, 51, 102));
		jButton36.setForeground(new java.awt.Color(255, 255, 102));
		jButton36.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 40);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 40);
			}
		});
		jButton37 = new javax.swing.JButton();
		jButton37.setBounds(170, 199, 155, 36);
		jButton37.setAlignmentY(0.0f);
		panel_guitar.add(jButton37);

		jButton37.setBackground(new java.awt.Color(255, 51, 102));
		jButton37.setForeground(new java.awt.Color(255, 255, 102));
		jButton37.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 41);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 41);
			}
		});
		jButton38 = new javax.swing.JButton();
		jButton38.setBounds(324, 199, 143, 36);
		jButton38.setAlignmentY(0.0f);
		panel_guitar.add(jButton38);

		jButton38.setBackground(new java.awt.Color(255, 51, 102));
		jButton38.setForeground(new java.awt.Color(255, 255, 102));
		jButton38.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 42);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 42);
			}
		});
		jButton39 = new javax.swing.JButton();
		jButton39.setBounds(466, 199, 139, 36);
		jButton39.setAlignmentY(0.0f);
		panel_guitar.add(jButton39);

		jButton39.setBackground(new java.awt.Color(255, 51, 102));
		jButton39.setForeground(new java.awt.Color(255, 255, 102));
		jButton39.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 43);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 43);
			}
		});
		jButton40 = new javax.swing.JButton();
		jButton40.setBounds(603, 199, 123, 36);
		jButton40.setAlignmentY(0.0f);
		panel_guitar.add(jButton40);

		jButton40.setBackground(new java.awt.Color(255, 51, 102));
		jButton40.setForeground(new java.awt.Color(255, 255, 102));
		jButton40.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 44);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 44);
			}
		});
		jButton41 = new javax.swing.JButton();
		jButton41.setBounds(725, 199, 116, 36);
		jButton41.setAlignmentY(0.0f);
		panel_guitar.add(jButton41);

		jButton41.setBackground(new java.awt.Color(255, 51, 102));
		jButton41.setForeground(new java.awt.Color(255, 255, 102));
		jButton41.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 45);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 45);
			}
		});
		jButton42 = new javax.swing.JButton();
		jButton42.setBounds(840, 199, 113, 36);
		jButton42.setAlignmentY(0.0f);
		panel_guitar.add(jButton42);
		jButton42.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			}
		});

		jButton42.setBackground(new java.awt.Color(255, 51, 102));
		jButton42.setForeground(new java.awt.Color(255, 255, 102));

		Component verticalStrut_29 = Box.createVerticalStrut(20);
		verticalStrut_29.setBounds(9, 235, 135, 36);
		panel_guitar.add(verticalStrut_29);

		Component verticalStrut_30 = Box.createVerticalStrut(20);
		verticalStrut_30.setBounds(144, 235, 135, 36);
		panel_guitar.add(verticalStrut_30);

		Component verticalStrut_31 = Box.createVerticalStrut(20);
		verticalStrut_31.setBounds(279, 235, 135, 36);
		panel_guitar.add(verticalStrut_31);

		Component verticalStrut_32 = Box.createVerticalStrut(20);
		verticalStrut_32.setBounds(414, 235, 135, 36);
		panel_guitar.add(verticalStrut_32);

		Component verticalStrut_33 = Box.createVerticalStrut(20);
		verticalStrut_33.setBounds(549, 235, 135, 36);
		panel_guitar.add(verticalStrut_33);

		Component verticalStrut_34 = Box.createVerticalStrut(20);
		verticalStrut_34.setBounds(684, 235, 135, 36);
		panel_guitar.add(verticalStrut_34);

		Component verticalStrut_35 = Box.createVerticalStrut(20);
		verticalStrut_35.setBounds(819, 235, 135, 36);
		panel_guitar.add(verticalStrut_35);

		Component verticalStrut_36 = Box.createVerticalStrut(20);
		verticalStrut_36.setBounds(9, 271, 135, 36);
		panel_guitar.add(verticalStrut_36);

		Component verticalStrut_37 = Box.createVerticalStrut(20);
		verticalStrut_37.setBounds(144, 271, 135, 36);
		panel_guitar.add(verticalStrut_37);

		Component verticalStrut_38 = Box.createVerticalStrut(20);
		verticalStrut_38.setBounds(279, 271, 135, 36);
		panel_guitar.add(verticalStrut_38);

		Component verticalStrut_39 = Box.createVerticalStrut(20);
		verticalStrut_39.setBounds(414, 271, 135, 36);
		panel_guitar.add(verticalStrut_39);

		Component verticalStrut_40 = Box.createVerticalStrut(20);
		verticalStrut_40.setBounds(549, 271, 135, 36);
		panel_guitar.add(verticalStrut_40);

		Component verticalStrut_41 = Box.createVerticalStrut(20);
		verticalStrut_41.setBounds(684, 271, 135, 36);
		panel_guitar.add(verticalStrut_41);

		Component verticalStrut_42 = Box.createVerticalStrut(20);
		verticalStrut_42.setBounds(819, 271, 135, 36);
		panel_guitar.add(verticalStrut_42);

		Component verticalStrut_43 = Box.createVerticalStrut(20);
		verticalStrut_43.setBounds(9, 307, 135, 36);
		panel_guitar.add(verticalStrut_43);

		Component verticalStrut_44 = Box.createVerticalStrut(20);
		verticalStrut_44.setBounds(144, 307, 135, 36);
		panel_guitar.add(verticalStrut_44);

		Component verticalStrut_45 = Box.createVerticalStrut(20);
		verticalStrut_45.setBounds(279, 307, 135, 36);
		panel_guitar.add(verticalStrut_45);

		Component verticalStrut_57 = Box.createVerticalStrut(20);
		verticalStrut_57.setBounds(414, 307, 135, 36);
		panel_guitar.add(verticalStrut_57);

		Component verticalStrut_58 = Box.createVerticalStrut(20);
		verticalStrut_58.setBounds(549, 307, 135, 36);
		panel_guitar.add(verticalStrut_58);

		Component verticalStrut_59 = Box.createVerticalStrut(20);
		verticalStrut_59.setBounds(684, 307, 135, 36);
		panel_guitar.add(verticalStrut_59);

		Component verticalStrut_60 = Box.createVerticalStrut(20);
		verticalStrut_60.setBounds(819, 307, 135, 36);
		panel_guitar.add(verticalStrut_60);

		Component verticalStrut_61 = Box.createVerticalStrut(20);
		verticalStrut_61.setBounds(9, 343, 135, 36);
		panel_guitar.add(verticalStrut_61);

		Component verticalStrut_62 = Box.createVerticalStrut(20);
		verticalStrut_62.setBounds(144, 343, 135, 36);
		panel_guitar.add(verticalStrut_62);

		Component verticalStrut_63 = Box.createVerticalStrut(20);
		verticalStrut_63.setBounds(279, 343, 135, 36);
		panel_guitar.add(verticalStrut_63);

		Component verticalStrut_64 = Box.createVerticalStrut(20);
		verticalStrut_64.setBounds(414, 343, 135, 36);
		panel_guitar.add(verticalStrut_64);

		Component verticalStrut_65 = Box.createVerticalStrut(20);
		verticalStrut_65.setBounds(549, 343, 135, 36);
		panel_guitar.add(verticalStrut_65);

		Component verticalStrut_66 = Box.createVerticalStrut(20);
		verticalStrut_66.setBounds(684, 343, 135, 36);
		panel_guitar.add(verticalStrut_66);

		Component verticalStrut_67 = Box.createVerticalStrut(20);
		verticalStrut_67.setBounds(819, 343, 135, 36);
		panel_guitar.add(verticalStrut_67);

		Component verticalStrut_68 = Box.createVerticalStrut(20);
		verticalStrut_68.setBounds(9, 379, 135, 36);
		panel_guitar.add(verticalStrut_68);

		Component verticalStrut_69 = Box.createVerticalStrut(20);
		verticalStrut_69.setBounds(144, 379, 135, 36);
		panel_guitar.add(verticalStrut_69);

		Component verticalStrut_70 = Box.createVerticalStrut(20);
		verticalStrut_70.setBounds(279, 379, 135, 36);
		panel_guitar.add(verticalStrut_70);

		Component verticalStrut_46 = Box.createVerticalStrut(20);
		verticalStrut_46.setBounds(414, 379, 135, 36);
		panel_guitar.add(verticalStrut_46);

		Component verticalStrut_47 = Box.createVerticalStrut(20);
		verticalStrut_47.setBounds(549, 379, 135, 36);
		panel_guitar.add(verticalStrut_47);

		Component verticalStrut_48 = Box.createVerticalStrut(20);
		verticalStrut_48.setBounds(684, 379, 135, 36);
		panel_guitar.add(verticalStrut_48);

		Component verticalStrut_49 = Box.createVerticalStrut(20);
		verticalStrut_49.setBounds(819, 379, 135, 36);
		panel_guitar.add(verticalStrut_49);

		Component verticalStrut_50 = Box.createVerticalStrut(20);
		verticalStrut_50.setBounds(9, 415, 135, 36);
		panel_guitar.add(verticalStrut_50);

		Component verticalStrut_51 = Box.createVerticalStrut(20);
		verticalStrut_51.setBounds(144, 415, 135, 36);
		panel_guitar.add(verticalStrut_51);

		Component verticalStrut_52 = Box.createVerticalStrut(20);
		verticalStrut_52.setBounds(279, 415, 135, 36);
		panel_guitar.add(verticalStrut_52);

		Component verticalStrut_53 = Box.createVerticalStrut(20);
		verticalStrut_53.setBounds(414, 415, 135, 36);
		panel_guitar.add(verticalStrut_53);

		Component verticalStrut_54 = Box.createVerticalStrut(20);
		verticalStrut_54.setBounds(549, 415, 135, 36);
		panel_guitar.add(verticalStrut_54);

		Component verticalStrut_55 = Box.createVerticalStrut(20);
		verticalStrut_55.setBounds(684, 415, 135, 36);
		panel_guitar.add(verticalStrut_55);

		Component verticalStrut_56 = Box.createVerticalStrut(20);
		verticalStrut_56.setBounds(819, 415, 135, 36);
		panel_guitar.add(verticalStrut_56);
		
		JLabel guitarBackgroundLabel = new JLabel();
		guitarBackgroundLabel.setBounds(10, 21, 943, 214);
		panel_guitar.add(guitarBackgroundLabel);
		
		File file = new File("./graphics/guitar2.png");
		
		try {
			BufferedImage bi = ImageIO.read(file);
			ImageIcon imgIcon = new ImageIcon(bi.getScaledInstance(943, 214, 10));
			guitarBackgroundLabel.setIcon(imgIcon);
		} catch (IOException ex) {
		}

		panel_bass = new JPanel();
		panel_bass.setBorder(new TitledBorder(null, "Instrument", TitledBorder.LEADING, TitledBorder.TOP, null, null));
		panel_instrument.add(panel_bass, "name_25798974278494");

		button = new JButton();
		button.setBounds(9, 19, 164, 48);
		button.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 43);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 43);
			}
		});
		panel_bass.setLayout(null);
		button.setForeground(new Color(255, 255, 102));
		button.setBackground(new Color(255, 51, 102));
		button.setAlignmentY(0.0f);
		panel_bass.add(button);

		button_1 = new JButton();
		button_1.setBounds(172, 19, 155, 48);
		button_1.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 44);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 44);
				requestFocusInWindow();
			}
		});
		button_1.setForeground(new Color(255, 255, 102));
		button_1.setBackground(new Color(255, 51, 102));
		button_1.setAlignmentY(0.0f);
		panel_bass.add(button_1);

		button_2 = new JButton();
		button_2.setBounds(326, 19, 143, 48);
		button_2.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 45);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 45);
			}
		});
		button_2.setForeground(new Color(255, 255, 102));
		button_2.setBackground(new Color(255, 51, 102));
		button_2.setAlignmentY(0.0f);
		panel_bass.add(button_2);

		button_3 = new JButton();
		button_3.setBounds(467, 19, 139, 48);
		button_3.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 46);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 46);
			}
		});
		button_3.setForeground(new Color(255, 255, 102));
		button_3.setBackground(new Color(255, 51, 102));
		button_3.setAlignmentY(0.0f);
		panel_bass.add(button_3);

		button_4 = new JButton();
		button_4.setBounds(605, 19, 123, 48);
		button_4.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 47);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 47);
			}
		});
		button_4.setForeground(new Color(255, 255, 102));
		button_4.setBackground(new Color(255, 51, 102));
		button_4.setAlignmentY(0.0f);
		panel_bass.add(button_4);

		button_5 = new JButton();
		button_5.setBounds(726, 19, 116, 48);
		button_5.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 48);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 48);
			}
		});
		button_5.setForeground(new Color(255, 255, 102));
		button_5.setBackground(new Color(255, 51, 102));
		button_5.setAlignmentY(0.0f);
		panel_bass.add(button_5);

		button_6 = new JButton();
		button_6.setBounds(841, 19, 113, 48);
		button_6.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 49);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 49);
			}
		});
		button_6.setForeground(new Color(255, 255, 102));
		button_6.setBackground(new Color(255, 51, 102));
		button_6.setAlignmentY(0.0f);
		panel_bass.add(button_6);

		button_7 = new JButton();
		button_7.setBounds(9, 67, 164, 48);
		button_7.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 38);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 38);
			}
		});
		button_7.setForeground(new Color(255, 255, 102));
		button_7.setBackground(new Color(255, 51, 102));
		button_7.setAlignmentY(0.0f);
		panel_bass.add(button_7);

		button_8 = new JButton();
		button_8.setBounds(172, 67, 155, 48);
		button_8.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 39);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 39);
			}
		});
		button_8.setForeground(new Color(255, 255, 102));
		button_8.setBackground(new Color(255, 51, 102));
		button_8.setAlignmentY(0.0f);
		panel_bass.add(button_8);

		button_9 = new JButton();
		button_9.setBounds(326, 67, 143, 48);
		button_9.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 40);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 40);
			}
		});
		button_9.setForeground(new Color(255, 255, 102));
		button_9.setBackground(new Color(255, 51, 102));
		button_9.setAlignmentY(0.0f);
		panel_bass.add(button_9);

		button_10 = new JButton();
		button_10.setBounds(467, 67, 139, 48);
		button_10.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 41);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 41);
			}
		});
		button_10.setForeground(new Color(255, 255, 102));
		button_10.setBackground(new Color(255, 51, 102));
		button_10.setAlignmentY(0.0f);
		panel_bass.add(button_10);

		button_11 = new JButton();
		button_11.setBounds(605, 67, 123, 48);
		button_11.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 42);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 42);
			}
		});
		button_11.setForeground(new Color(255, 255, 102));
		button_11.setBackground(new Color(255, 51, 102));
		button_11.setAlignmentY(0.0f);
		panel_bass.add(button_11);

		button_12 = new JButton();
		button_12.setBounds(726, 67, 116, 48);
		button_12.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 43);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 43);
			}
		});
		button_12.setForeground(new Color(255, 255, 102));
		button_12.setBackground(new Color(255, 51, 102));
		button_12.setAlignmentY(0.0f);
		panel_bass.add(button_12);

		button_13 = new JButton();
		button_13.setBounds(841, 67, 113, 48);
		button_13.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 44);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 44);
			}
		});
		button_13.setForeground(new Color(255, 255, 102));
		button_13.setBackground(new Color(255, 51, 102));
		button_13.setAlignmentY(0.0f);
		panel_bass.add(button_13);

		button_14 = new JButton();
		button_14.setBounds(9, 115, 164, 48);
		button_14.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 33);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 33);
			}
		});
		button_14.setForeground(new Color(255, 255, 102));
		button_14.setBackground(new Color(255, 51, 102));
		button_14.setAlignmentY(0.0f);
		panel_bass.add(button_14);

		button_15 = new JButton();
		button_15.setBounds(172, 115, 155, 48);
		button_15.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 34);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 34);
			}
		});
		button_15.setForeground(new Color(255, 255, 102));
		button_15.setBackground(new Color(255, 51, 102));
		button_15.setAlignmentY(0.0f);
		panel_bass.add(button_15);

		button_16 = new JButton();
		button_16.setBounds(326, 115, 143, 48);
		button_16.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 35);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 35);
			}
		});
		button_16.setForeground(new Color(255, 255, 102));
		button_16.setBackground(new Color(255, 51, 102));
		button_16.setAlignmentY(0.0f);
		panel_bass.add(button_16);

		button_17 = new JButton();
		button_17.setBounds(467, 115, 139, 48);
		button_17.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 36);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 36);
			}
		});
		button_17.setForeground(new Color(255, 255, 102));
		button_17.setBackground(new Color(255, 51, 102));
		button_17.setAlignmentY(0.0f);
		panel_bass.add(button_17);

		button_18 = new JButton();
		button_18.setBounds(605, 115, 123, 48);
		button_18.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 37);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 37);
			}
		});
		button_18.setForeground(new Color(255, 255, 102));
		button_18.setBackground(new Color(255, 51, 102));
		button_18.setAlignmentY(0.0f);
		panel_bass.add(button_18);

		button_19 = new JButton();
		button_19.setBounds(726, 115, 116, 48);
		button_19.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 38);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 38);
			}
		});
		button_19.setForeground(new Color(255, 255, 102));
		button_19.setBackground(new Color(255, 51, 102));
		button_19.setAlignmentY(0.0f);
		panel_bass.add(button_19);

		button_20 = new JButton();
		button_20.setBounds(841, 115, 113, 48);
		button_20.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 39);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 39);
			}
		});
		button_20.setForeground(new Color(255, 255, 102));
		button_20.setBackground(new Color(255, 51, 102));
		button_20.setAlignmentY(0.0f);
		panel_bass.add(button_20);

		button_21 = new JButton();
		button_21.setBounds(9, 163, 164, 48);
		button_21.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 28);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 28);
			}
		});
		button_21.setForeground(new Color(255, 255, 102));
		button_21.setBackground(new Color(255, 51, 102));
		button_21.setAlignmentY(0.0f);
		panel_bass.add(button_21);

		button_22 = new JButton();
		button_22.setBounds(172, 163, 155, 48);
		button_22.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 29);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 29);
			}
		});
		button_22.setForeground(new Color(255, 255, 102));
		button_22.setBackground(new Color(255, 51, 102));
		button_22.setAlignmentY(0.0f);
		panel_bass.add(button_22);

		button_23 = new JButton();
		button_23.setBounds(326, 163, 143, 48);
		button_23.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 30);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 30);
			}
		});
		button_23.setForeground(new Color(255, 255, 102));
		button_23.setBackground(new Color(255, 51, 102));
		button_23.setAlignmentY(0.0f);
		panel_bass.add(button_23);

		button_24 = new JButton();
		button_24.setBounds(467, 163, 139, 48);
		button_24.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 31);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 31);
			}
		});
		button_24.setForeground(new Color(255, 255, 102));
		button_24.setBackground(new Color(255, 51, 102));
		button_24.setAlignmentY(0.0f);
		panel_bass.add(button_24);

		button_25 = new JButton();
		button_25.setBounds(605, 163, 123, 48);
		button_25.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 32);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 32);
			}
		});
		button_25.setForeground(new Color(255, 255, 102));
		button_25.setBackground(new Color(255, 51, 102));
		button_25.setAlignmentY(0.0f);
		panel_bass.add(button_25);

		button_26 = new JButton();
		button_26.setBounds(726, 163, 116, 48);
		button_26.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 33);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 33);
			}
		});
		button_26.setForeground(new Color(255, 255, 102));
		button_26.setBackground(new Color(255, 51, 102));
		button_26.setAlignmentY(0.0f);
		panel_bass.add(button_26);

		button_27 = new JButton();
		button_27.setBounds(841, 163, 113, 48);
		button_27.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 34);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 34);
			}
		});
		button_27.setForeground(new Color(255, 255, 102));
		button_27.setBackground(new Color(255, 51, 102));
		button_27.setAlignmentY(0.0f);
		panel_bass.add(button_27);

		Component verticalStrut_1 = Box.createVerticalStrut(20);
		verticalStrut_1.setBounds(9, 211, 135, 48);
		panel_bass.add(verticalStrut_1);

		Component verticalStrut = Box.createVerticalStrut(20);
		verticalStrut.setBounds(144, 211, 135, 48);
		panel_bass.add(verticalStrut);

		Component verticalStrut_2 = Box.createVerticalStrut(20);
		verticalStrut_2.setBounds(279, 211, 135, 48);
		panel_bass.add(verticalStrut_2);

		Component verticalStrut_3 = Box.createVerticalStrut(20);
		verticalStrut_3.setBounds(414, 211, 135, 48);
		panel_bass.add(verticalStrut_3);

		Component verticalStrut_7 = Box.createVerticalStrut(20);
		verticalStrut_7.setBounds(549, 211, 135, 48);
		panel_bass.add(verticalStrut_7);

		Component verticalStrut_4 = Box.createVerticalStrut(20);
		verticalStrut_4.setBounds(684, 211, 135, 48);
		panel_bass.add(verticalStrut_4);

		Component verticalStrut_5 = Box.createVerticalStrut(20);
		verticalStrut_5.setBounds(819, 211, 135, 48);
		panel_bass.add(verticalStrut_5);

		Component verticalStrut_6 = Box.createVerticalStrut(20);
		verticalStrut_6.setBounds(9, 259, 135, 48);
		panel_bass.add(verticalStrut_6);

		verticalStrut_8 = Box.createVerticalStrut(20);
		verticalStrut_8.setBounds(144, 259, 135, 48);
		panel_bass.add(verticalStrut_8);

		verticalStrut_9 = Box.createVerticalStrut(20);
		verticalStrut_9.setBounds(279, 259, 135, 48);
		panel_bass.add(verticalStrut_9);

		verticalStrut_10 = Box.createVerticalStrut(20);
		verticalStrut_10.setBounds(414, 259, 135, 48);
		panel_bass.add(verticalStrut_10);

		verticalStrut_11 = Box.createVerticalStrut(20);
		verticalStrut_11.setBounds(549, 259, 135, 48);
		panel_bass.add(verticalStrut_11);

		verticalStrut_12 = Box.createVerticalStrut(20);
		verticalStrut_12.setBounds(684, 259, 135, 48);
		panel_bass.add(verticalStrut_12);

		verticalStrut_13 = Box.createVerticalStrut(20);
		verticalStrut_13.setBounds(819, 259, 135, 48);
		panel_bass.add(verticalStrut_13);

		verticalStrut_14 = Box.createVerticalStrut(20);
		verticalStrut_14.setBounds(9, 307, 135, 48);
		panel_bass.add(verticalStrut_14);

		verticalStrut_15 = Box.createVerticalStrut(20);
		verticalStrut_15.setBounds(144, 307, 135, 48);
		panel_bass.add(verticalStrut_15);

		verticalStrut_16 = Box.createVerticalStrut(20);
		verticalStrut_16.setBounds(279, 307, 135, 48);
		panel_bass.add(verticalStrut_16);

		verticalStrut_17 = Box.createVerticalStrut(20);
		verticalStrut_17.setBounds(414, 307, 135, 48);
		panel_bass.add(verticalStrut_17);

		verticalStrut_18 = Box.createVerticalStrut(20);
		verticalStrut_18.setBounds(549, 307, 135, 48);
		panel_bass.add(verticalStrut_18);

		verticalStrut_19 = Box.createVerticalStrut(20);
		verticalStrut_19.setBounds(684, 307, 135, 48);
		panel_bass.add(verticalStrut_19);

		verticalStrut_20 = Box.createVerticalStrut(20);
		verticalStrut_20.setBounds(819, 307, 135, 48);
		panel_bass.add(verticalStrut_20);

		verticalStrut_21 = Box.createVerticalStrut(20);
		verticalStrut_21.setBounds(9, 355, 135, 48);
		panel_bass.add(verticalStrut_21);

		verticalStrut_22 = Box.createVerticalStrut(20);
		verticalStrut_22.setBounds(144, 355, 135, 48);
		panel_bass.add(verticalStrut_22);

		verticalStrut_23 = Box.createVerticalStrut(20);
		verticalStrut_23.setBounds(279, 355, 135, 48);
		panel_bass.add(verticalStrut_23);

		verticalStrut_24 = Box.createVerticalStrut(20);
		verticalStrut_24.setBounds(414, 355, 135, 48);
		panel_bass.add(verticalStrut_24);

		verticalStrut_25 = Box.createVerticalStrut(20);
		verticalStrut_25.setBounds(549, 355, 135, 48);
		panel_bass.add(verticalStrut_25);

		verticalStrut_26 = Box.createVerticalStrut(20);
		verticalStrut_26.setBounds(684, 355, 135, 48);
		panel_bass.add(verticalStrut_26);

		verticalStrut_27 = Box.createVerticalStrut(20);
		verticalStrut_27.setBounds(819, 355, 135, 48);
		panel_bass.add(verticalStrut_27);

		verticalStrut_28 = Box.createVerticalStrut(20);
		verticalStrut_28.setBounds(9, 403, 135, 48);
		panel_bass.add(verticalStrut_28);
		
		JLabel bassBackgroundLabel = new JLabel("");
		bassBackgroundLabel.setBounds(9, 19, 950, 200);
		panel_bass.add(bassBackgroundLabel);
		
		File fileBass = new File("./graphics/bass.png");
		
		try {
			BufferedImage bi = ImageIO.read(fileBass);
			ImageIcon imgIcon = new ImageIcon(bi.getScaledInstance(943, 180, 10));
			bassBackgroundLabel.setIcon(imgIcon);
		} catch (IOException ex) {
		}
		Component []compTab = panel_bass.getComponents();
		for (int i=0; i<compTab.length; i++){
			if (compTab[i] instanceof JButton){
				JButton tmp = (JButton) compTab[i];
				tmp.setOpaque(false);
				lista2.add(tmp);

			}
		}
			
		panel_keyboard = new Piano();
		
		//////////////////////
		//panel_keyboard.player = this.player;
		//panel_keyboard.player = this.player;
		panel_instrument.add(panel_keyboard, "name_25798994740667");
		jButton42.addMouseListener(new java.awt.event.MouseListener() {

			@Override
			public void mouseClicked(MouseEvent arg0) {
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				player.playNote((char) 46);

			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				player.playNoteStop((char) 46);
			}
		});
		getContentPane().setLayout(layout);

		pack();
		jPanel2.setVisible(true);
		panel.setVisible(true);
	}// </editor-fold>

	private void inicjalizuj() {

		lista.add(jButton1);
		lista.add(jButton2);
		lista.add(jButton3);
		lista.add(jButton4);
		lista.add(jButton5);
		lista.add(jButton6);
		lista.add(jButton7);
		lista.add(jButton8);
		lista.add(jButton9);
		lista.add(jButton10);
		lista.add(jButton11);
		lista.add(jButton12);
		lista.add(jButton13);
		lista.add(jButton14);
		lista.add(jButton15);
		lista.add(jButton16);
		lista.add(jButton17);
		lista.add(jButton18);
		lista.add(jButton19);
		lista.add(jButton20);
		lista.add(jButton21);
		lista.add(jButton22);
		lista.add(jButton23);
		lista.add(jButton24);
		lista.add(jButton25);
		lista.add(jButton26);
		lista.add(jButton27);
		lista.add(jButton28);
		lista.add(jButton29);
		lista.add(jButton30);
		lista.add(jButton31);
		lista.add(jButton32);
		lista.add(jButton33);
		lista.add(jButton34);
		lista.add(jButton35);
		lista.add(jButton36);
		lista.add(jButton37);
		lista.add(jButton38);
		lista.add(jButton39);
		lista.add(jButton40);
		lista.add(jButton41);
		lista.add(jButton42);

	}
	
	
	//pianino
		

	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton13;
	private javax.swing.JButton jButton14;
	private javax.swing.JButton jButton15;
	private javax.swing.JButton jButton16;
	private javax.swing.JButton jButton17;
	private javax.swing.JButton jButton18;
	private javax.swing.JButton jButton19;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton20;
	private javax.swing.JButton jButton21;
	private javax.swing.JButton jButton22;
	private javax.swing.JButton jButton23;
	private javax.swing.JButton jButton24;
	private javax.swing.JButton jButton25;
	private javax.swing.JButton jButton26;
	private javax.swing.JButton jButton27;
	private javax.swing.JButton jButton28;
	private javax.swing.JButton jButton29;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton30;
	private javax.swing.JButton jButton31;
	private javax.swing.JButton jButton32;
	private javax.swing.JButton jButton33;
	private javax.swing.JButton jButton34;
	private javax.swing.JButton jButton35;
	private javax.swing.JButton jButton36;
	private javax.swing.JButton jButton37;
	private javax.swing.JButton jButton38;
	private javax.swing.JButton jButton39;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton40;
	private javax.swing.JButton jButton41;
	private javax.swing.JButton jButton42;
	private javax.swing.JButton jButton43;
	private javax.swing.JButton jButton44;
	private javax.swing.JButton jButton45;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JButton jButton46;
	private javax.swing.JButton jButton47;
	private javax.swing.JButton jButton48;
	private javax.swing.JButton jButton49;
	private javax.swing.JButton jButton50;
	private javax.swing.JButton jButton51;
	private javax.swing.JButton jButton52;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JPanel jPanel2;
	private ArrayList<JButton> lista;
	private ArrayList<JButton> lista2;
	private JPanel panel;
	private JPanel panel_guitar;
	private JPanel panel_bass;
	private JButton button;
	private JButton button_1;
	private JButton button_2;
	private JButton button_3;
	private JButton button_4;
	private JButton button_5;
	private JButton button_6;
	private JButton button_7;
	private JButton button_8;
	private JButton button_9;
	private JButton button_10;
	private JButton button_11;
	private JButton button_12;
	private JButton button_13;
	private JButton button_14;
	private JButton button_15;
	private JButton button_16;
	private JButton button_17;
	private JButton button_18;
	private JButton button_19;
	private JButton button_20;
	private JButton button_21;
	private JButton button_22;
	private JButton button_23;
	private JButton button_24;
	private JButton button_25;
	private JButton button_26;
	private JButton button_27;
	private Piano panel_keyboard;
	private JPanel panel_instrument;
	private Component verticalStrut_8;
	private Component verticalStrut_9;
	private Component verticalStrut_10;
	private Component verticalStrut_11;
	private Component verticalStrut_12;
	private Component verticalStrut_13;
	private Component verticalStrut_14;
	private Component verticalStrut_15;
	private Component verticalStrut_16;
	private Component verticalStrut_17;
	private Component verticalStrut_18;
	private Component verticalStrut_19;
	private Component verticalStrut_20;
	private Component verticalStrut_21;
	private Component verticalStrut_22;
	private Component verticalStrut_23;
	private Component verticalStrut_24;
	private Component verticalStrut_25;
	private Component verticalStrut_26;
	private Component verticalStrut_27;
	private Component verticalStrut_28;
	private JLabel labelBassBackground;
}


class Piano extends javax.swing.JPanel {

    /**
     * Creates new form Piano
     */
    public Piano() {
        initComponents();
        lista = new ArrayList<JButton>();
        inicjalizuj();
        //player = new GarageBandPlayer();
        
        for(JButton przycisk:lista){
            
            przycisk.setOpaque(false);
            przycisk.setContentAreaFilled(false);
            //przycisk.setBorderPainted(false); 
        }
        
        this.setSize(963, 460);
        
    }

    /**
     * initialize all of the components 
     */
    
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        
        
        setLayout(null);
        add(jButton1);
        jButton1.setBounds(70, 260, 70, 200);
		jButton1.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 62);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 62);
			}
		});
        add(jButton2);
        jButton2.setBounds(130, 260, 70, 200);
		jButton2.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 64);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 64);
			}
		});
        add(jButton3);
        jButton3.setBounds(200, 260, 70, 200);
		jButton3.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 65);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 65);
			}
		});
        add(jButton4);
        jButton4.setBounds(270, 260, 70, 200);
		jButton4.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 67);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 67);
			}
		});
        add(jButton5);
        jButton5.setBounds(340, 260, 70, 200);
		jButton5.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 69);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 69);
			}
		});
        add(jButton6);
        jButton6.setBounds(410, 260, 70, 200);
		jButton6.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 71);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 71);
			}
		});
        add(jButton7);
        jButton7.setBounds(480, 260, 70, 200);
		jButton7.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 72);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 72);
			}
		});
        add(jButton8);
        jButton8.setBounds(550, 260, 70, 200);
		jButton8.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 74);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 74);
			}
		});
        add(jButton9);
        jButton9.setBounds(620, 260, 70, 200);
		jButton9.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 76);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 76);
			}
		});
        add(jButton10);
        jButton10.setBounds(690, 260, 70, 200);
		jButton10.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 77);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 77);
			}
		});
        add(jButton11);
        jButton11.setBounds(760, 260, 70, 200);
		jButton11.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 79);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 79);
			}
		});
        add(jButton12);
        jButton12.setBounds(830, 260, 70, 200);
		jButton12.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 81);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 81);
			}
		});
        add(jButton13);
        jButton13.setBounds(900, 260, 70, 200);
		jButton13.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 83);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 83);
			}
		});
        add(jButton14);
        jButton14.setBounds(0, 260, 70, 200);
		jButton14.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 60);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 60);
			}
		});
        add(jButton15);
        jButton15.setBounds(120, 0, 40, 260);
		jButton15.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 63);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 63);
			}
		});
        add(jButton16);
        jButton16.setBounds(260, 0, 40, 260);
		jButton16.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 66);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 66);
			}
		});
        add(jButton17);
        jButton17.setBounds(320, 0, 40, 260);
		jButton17.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 68);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 68);
			}
		});
        add(jButton18);
        jButton18.setBounds(390, 0, 40, 260);
		jButton18.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 70);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 70);
			}
		});
        add(jButton19);
        jButton19.setBounds(530, 0, 40, 260);
		jButton19.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 73);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 73);
			}
		});
        add(jButton20);
        jButton20.setBounds(600, 0, 40, 260);
		jButton20.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 75);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 75);
			}
		});
        add(jButton21);
        jButton21.setBounds(740, 0, 40, 260);
		jButton21.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 78);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 78);
			}
		});
        add(jButton22);
        jButton22.setBounds(810, 0, 40, 260);
		jButton22.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 80);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 80);
			}
		});
        add(jButton23);
        jButton23.setBounds(880, 0, 40, 260);
		jButton23.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 82);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 82);
			}
		});
        add(jButton24);
        jButton24.setBounds(50, 0, 40, 260);
		jButton24.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				player.playNote((char) 61);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				player.playNoteStop((char) 61);
			}
		});

        jLabel1.setIcon(new javax.swing.ImageIcon("./graphics/piano.jpg")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 963, 460);
    }

    
    /**
     * adding all buttons to one array list to control these button more comfortably 
     */

    	private void inicjalizuj() {

		lista.add(jButton1);
		lista.add(jButton2);
		lista.add(jButton3);
		lista.add(jButton4);
		lista.add(jButton5);
		lista.add(jButton6);
		lista.add(jButton7);
		lista.add(jButton8);
		lista.add(jButton9);
		lista.add(jButton10);
		lista.add(jButton11);
		lista.add(jButton12);
		lista.add(jButton13);
		lista.add(jButton14);
		lista.add(jButton15);
		lista.add(jButton16);
		lista.add(jButton17);
		lista.add(jButton18);
		lista.add(jButton19);
		lista.add(jButton20);
		lista.add(jButton21);
		lista.add(jButton22);
		lista.add(jButton23);
		lista.add(jButton24);


	}
        
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    public GarageBandPlayer player;
    // End of variables declaration//GEN-END:variables
    ArrayList<JButton> lista;

}
